- img: site.png
  cta: "Preciso de um site"

- img: catalogo.png
  cta: "Preciso de um catálogo"

- img: instagram.png
  cta: "Preciso estar no Instagram"

- img: info.png
  cta: "Gostei mas tenho dúvidas"
